# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.3.9-hotspot

# Fabric Properties
minecraft_version=26.1
yarn_mappings=26.1+build.1
loader_version=0.15.11

# Dependencies
fabric_version=0.100.4+26.1

# Mod Properties
mod_version = 1.5.2+mc26.1
maven_group = net.dkxly.fabridash_resurrected
archives_base_name = fabridash_resurrected
